public enum EPoolObjectType
{
    Default,
    PlayerDamageText,
    EnemyDamageText,
    SpawnEffect,
    EnemyBullet,
    BuffEffect,
    BuffAreaEffect,
    _StartSmallEnemyType = 1000,
    Catcher_S = 1001,
    FishGuard_S ,
    Knight_S ,
    Monkeydong_S ,
    Wedger_S ,
    Trestor_S,
    Imp_S,
    PitBoy_S,
    Nosedman_S,
    Spike_S,
    _EndSmallEnemyType,
    _StartMediumEnemyType = 2000,
    Catcher_M ,
    FishGuard_M ,
    Knight_M ,
    Monkeydong_M ,
    Wedger_M ,
    Trestor_M,
    Imp_M,
    Nosedman_M,
    Spike_M,
    _EndMediumEnemyType,
    _StartLargeEnemyType = 3000,
    Catcher_L ,
    FishGuard_L ,
    Knight_L ,
    Monkeydong_L ,
    Wedger_L ,
    Trestor_L,
    Imp_L,
    PitBoy_L,
    Nosedman_L,
    Spike_L,
    _EndLargeEnemyType,
}
